export const genereColor = {
  default: 'bg-gray-200 text-gray-800',
  romance: 'bg-pink-300 text-pink-800',
  comedy: 'bg-yellow-300 text-yellow-800',
  'slice of life': 'bg-neutral-300 text-neutral-800',
  drama: 'bg-red-700 text-red-100',
  action: 'bg-red-500 text-white',
  adventure: 'bg-orange-400 text-orange-800',
  fantasy: 'bg-purple-300 text-purple-800',
  isekai: 'bg-indigo-300 text-indigo-800',
  "girls' love": 'bg-pink-400 text-pink-800',
  sports: 'bg-green-500 text-green-50',
  crime: 'bg-gray-600 text-gray-100',
  psychological: 'bg-stone-400 text-stone-800',
  horror: 'bg-red-100 text-red-500',
  'sci-fi': 'bg-sky-600 text-sky-100',
  historical: 'bg-amber-700 text-amber-100',
  thriller: 'bg-violet-700 text-violet-100',
  superhero: 'bg-blue-600 text-blue-100',
};

export const genres = [
  'Action',
  'Adventure',
  "Boys' Love",
  'Comedy',
  'Crime',
  'Drama',
  'Fantasy',
  "Girls' Love",
  'Historical',
  'Horror',
  'Isekai',
  'Magical Girls',
  'Mecha',
  'Medical',
  'Mystery',
  'Philosophical',
  'Psychological',
  'Romance',
  'Sci-Fi',
  'Slice of Life',
  'Sports',
  'Superhero',
  'Thriller',
  'Tragedy',
  'Wuxia',
];

export const theme = [
  "Aliens",
  "Animals",
  "Cooking",
  "Crossdressing",
  "Delinquents",
  "Demons",
  "Genderswap",
  "Ghosts",
  "Gyaru",
  "Harem",
  "Incest",
  "Loli",
  "Mafia",
  "Magic",
  "Martial Arts",
  "Military",
  "Monster Girls",
  "Monsters",
  "Music",
  "Ninja",
  "Office Workers",
  "Police",
  "Post-Apocalyptic",
  "Reincarnation",
  "Reverse Harem",
  "Samurai",
  "School Life",
  "Shota",
  "Supernatural",
  "Survival",
  "Time Travel",
  "Traditional Games",
  "Vampires",
  "Video Games",
  "Villainess",
  "Virtual Reality",
  "Zombies"
];

export const status = ["Ongoing", "Completed", "Hiatus", "Cancelled"];
